# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - IU-Quiz

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Build Backend
        run: |
          npm install
          cd backend
          
        id: backend

      - name: Build Frontend
        run: |
          cd app
          npm install
          npm run build --if-present
        id: frontend

      - name: Upload Backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: backend

      - name: Upload Frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download Backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend

      - name: Deploy to Azure Web App Backend
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp-backend
        with:
          app-name: 'IU-Quiz'
          slot-name: 'Production'
          package: backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9C1D2C94EB79480E98E60172101B311B }}

      - name: Download Frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend

      - name: Deploy to Azure Web App Frontend
        id: deploy-to-webapp-frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'IU-Quiz-Frontend'
          slot-name: 'production'
          package: app
          publish-profile: ${{ secrets.PUBLISH_FRONTEND }}

