name: Build and deploy Node.js app to Azure Web Apps - IU-Quiz

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Build Backend
        run: |
          cd backend
          npm install

      - name: Build Frontend
        run: |
          cd app
          npm install
          npm run build --if-present

      - name: Upload Backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-app
          path: ./backend

      - name: Upload Frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-app
          path: ./frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-app

      - name: Deploy to Azure Web App Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'IU-Quiz'
          package: ./backend

      - name: Download Frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-app

      - name: Deploy to Azure Web App Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'IU-Quiz-Frontend'
          package: ./frontend
